#ifndef ACCOUNTVIEW_H
#define ACCOUNTVIEW_H

#include <QMainWindow>
#include <QWidget>
#include <QVBoxLayout>
#include "stockview.h"
#include "../ViewModel/accountviewmodel.h"

namespace Ui {
class accountview;
}

/**
 * @class accountview
 * @brief Main window for displaying and interacting with a single Account.
 *
 * The accountview class provides a UI that shows current stock holdings,
 * allows buying/selling of stocks, and displays account balance updates.
 */
class accountview : public QMainWindow {
    Q_OBJECT

public:
    /**
     * @brief Constructs an accountview window.
     * @param parent Optional parent QWidget pointer.
     */
    explicit accountview(QWidget *parent = nullptr);

    /**
     * @brief Destructor for accountview.
     */
    ~accountview();

    /**
     * @brief Creates the placeholder widget(s) for individual stock views.
     *
     * Sets up the layout where each stockview will be added.
     */
    void makeStockview();

    /**
     * @brief Associates an AccountViewModel with this view.
     * @param viewModel Pointer to the AccountViewModel.
     */
    void setViewmodel(AccountViewModel* viewModel);

    /**
     * @brief Generates individual stockview widgets based on the ViewModel.
     *
     * Iterates over stockViewModels and instantiates stockview objects.
     */
    void generateStockView();

private slots:
    /**
     * @brief Slot called when the "Buy" button is pressed.
     *
     * Delegates the buy action to the associated AccountViewModel.
     */
    void pushBuyButton();

    /**
     * @brief Slot called when the "Sell" button is pressed.
     *
     * Delegates the sell action to the associated AccountViewModel.
     */
    void pushSellButton();

    /**
     * @brief Slot to update the displayed balance whenever it changes.
     * @param value The new balance value.
     */
    void updateBalanceDisplay(float value);

private:
    Ui::accountview *ui;               ///< Pointer to the UI elements generated by Qt Designer.
    QVector<stockview*> stocks;        ///< List of stockview widgets displayed.
    AccountViewModel* viewModel;       ///< Associated ViewModel for this account.
};

#endif // ACCOUNTVIEW_H

