#ifndef STOCKVIEW_H
#define STOCKVIEW_H

#include "../ViewModel/stockviewmodel.h"
#include <QMainWindow>
#include <QLabel>

namespace Ui {
class stockview;
}

/**
 * @class stockview
 * @brief QWidget-based view class for displaying stock information.
 *
 * The stockview class displays the stock ID and current amount, and updates when
 * the underlying StockViewModel emits amountChanged().
 */
class stockview : public QMainWindow {
    Q_OBJECT

public:
    /**
     * @brief Constructs a stockview widget.
     * @param parent Optional parent QWidget pointer.
     */
    explicit stockview(QWidget *parent = nullptr);

    /**
     * @brief Destructor for stockview.
     */
    ~stockview();

    /**
     * @brief Associates a StockViewModel with this view.
     *
     * Connects the model’s amountChanged signal to this view’s update slot.
     *
     * @param viewModel Pointer to the StockViewModel.
     */
    void setViewmodel(StockViewModel *viewModel);

    /**
     * @brief Gets the associated StockViewModel.
     * @return Pointer to the StockViewModel.
     */
    StockViewModel *getviewModel() { return viewModel; }

private slots:
    /**
     * @brief Slot to update the displayed amount when the model changes.
     * @param newAmount Updated number of shares from the model.
     */
    void updateAmountDisplay(int newAmount);

private:
    Ui::stockview *ui;             ///< Pointer to the UI elements generated by Qt Designer.
    StockViewModel *viewModel = nullptr; ///< Associated ViewModel for this stock.
};

#endif // STOCKVIEW_H
