#ifndef USERVIEW_H
#define USERVIEW_H

#include <QMainWindow>
#include <QVBoxLayout>
#include "accountview.h"
#include "../ViewModel/userviewmodel.h"
#include <QScrollArea>

namespace Ui {
class userview;
}

/**
 * @class userview
 * @brief Main window for displaying and interacting with a User’s multiple accounts.
 *
 * The userview class creates a scrollable list of accountview widgets, one per
 * account owned by the user. It updates whenever the UserViewModel provides new accounts.
 */
class userview : public QMainWindow {
    Q_OBJECT

public:
    /**
     * @brief Constructs a userview window.
     * @param parent Optional parent QWidget pointer.
     */
    explicit userview(QWidget *parent = nullptr);

    /**
     * @brief Destructor for userview.
     */
    ~userview();

    /**
     * @brief Associates a UserViewModel with this view.
     * @param viewmodel Pointer to the UserViewModel.
     */
    void setViewmodel(UserViewModel* viewmodel);

    /**
     * @brief Creates placeholder QWidget(s) for each accountview.
     *
     * Prepares the layout where accountview widgets will be added.
     */
    void makeAccountView();

    /**
     * @brief Generates accountview widgets based on the ViewModel’s account list.
     *
     * Iterates over accountViewModels and instantiates accountview objects.
     */
    void generateAccountView();

signals:
    /**
     * @brief Emitted when any stock’s amount changes in a subview.
     * @param newAmount The updated number of shares.
     */
    void amountChanged(int newAmount);

private:
    Ui::userview *ui;                     ///< Pointer to the UI elements generated by Qt Designer.
    QVector<accountview*> accounts;       ///< List of accountview widgets displayed.
    UserViewModel* viewModel;             ///< Associated ViewModel for this user.
};

#endif // USERVIEW_H
